import type { NextPage } from 'next'
import Head from 'next/head'
import Header from '../components/header/Header'
import styles from '../styles/Home.module.scss'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <main className={styles.main}>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. At a sequi suscipit, laboriosam obcaecati dignissimos natus nulla, veniam, iure veritatis debitis officia dicta dolor. Rem, obcaecati unde? Ut aliquam dolorem, aliquid ad explicabo harum vel aspernatur sequi libero expedita voluptatibus eligendi ratione assumenda? Recusandae libero, repellat molestiae ut magnam exercitationem!
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}

export default Home
